{{- if .Values.rbac.create }}
kind: ServiceAccount
apiVersion: v1
metadata:
  namespace: {{ .Release.Namespace | quote }}
  name: {{ .Values.controllerManager.serviceAccount }}
  labels:
    {{- include "chaos-mesh.labels" . | nindent 4 }}
    app.kubernetes.io/component: controller-manager

---
# roles
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Release.Name }}-chaos-controller-manager-target-namespace
  labels:
    {{- include "chaos-mesh.labels" . | nindent 4 }}
    app.kubernetes.io/component: controller-manager
rules:
  - apiGroups: [ "" ]
    resources: [ "endpoints" ]
    verbs: [ "get", "list", "watch" ]
  - apiGroups: [ "" ]
    resources: [ "pods", "secrets" ]
    verbs: [ "get", "list", "watch", "delete", "update" ]
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - patch
      - create
  - apiGroups: [ "" ]
    resources: [ "configmaps" ]
    verbs: [ "*" ]
  - apiGroups: [ "chaos-mesh.org" ]
    resources:
      - "*"
    verbs: [ "*" ]
  - apiGroups: [ "" ]
    resources: [ "services" ]
    verbs: [ "get", "list", "watch" ]

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Release.Name }}-chaos-controller-manager-cluster-level
  labels:
    {{- include "chaos-mesh.labels" . | nindent 4 }}
    app.kubernetes.io/component: controller-manager
rules:
  - apiGroups: [ "" ]
    resources:
      - nodes
{{- if .Values.clusterScoped }}
      - namespaces
{{- end }}
    verbs: [ "get", "list", "watch" ]
  - apiGroups: [ "authorization.k8s.io" ]
    resources:
      - subjectaccessreviews
    verbs: [ "create" ]

---
# bindings cluster level
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Release.Name }}-chaos-controller-manager-cluster-level
  labels:
    {{- include "chaos-mesh.labels" . | nindent 4 }}
    app.kubernetes.io/component: controller-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Release.Name }}-chaos-controller-manager-cluster-level
subjects:
  - kind: ServiceAccount
    name: {{ .Values.controllerManager.serviceAccount }}
    namespace: {{ .Release.Namespace | quote }}

---
{{- if .Values.clusterScoped }}
kind: ClusterRoleBinding
{{- else }}
kind: RoleBinding
{{- end }}
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Release.Name }}-chaos-controller-manager-target-namespace
{{- if not .Values.clusterScoped }}
  namespace: {{ .Values.controllerManager.targetNamespace | quote }}
{{- end }}
  labels:
    {{- include "chaos-mesh.labels" . | nindent 4 }}
    app.kubernetes.io/component: controller-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Release.Name }}-chaos-controller-manager-target-namespace
subjects:
  - kind: ServiceAccount
    name: {{ .Values.controllerManager.serviceAccount }}
    namespace: {{ .Release.Namespace | quote }}
{{- end }}
