header:
  license:
    spdx-id: Apache-2.0
    copyright-owner: Chaos Mesh Authors.
  paths-ignore:
    - '.gitignore'
    - '.dockerignore'
    - '.editorconfig'
    - '.muse.toml'
    - '**/*.md'
    - '**/*.json'
    - '**/go.mod'
    - '**/go.sum'
    - 'LICENSE'
    - '.github/workflows/*'
    - '.github/.licenserc.yaml'
    - 'Makefile'
    - 'PROJECT'
    - 'LICENSE'
    - 'ui/.prettierignore'
    # reported as unsupported by skywalking-eyes as of October 4th 2021
    - 'helm/chaos-mesh/.helmignore'
    - 'helm/chaos-mesh/templates/_helpers.tpl'
    - 'pkg/chaosdaemon/pb/chaosdaemon.proto'
    - 'pkg/chaoskernel/pb/bpfki.proto'
    - 'test/integration_test/utils/check_contains'
    - 'ui/.prettierrc'
    - 'ui/src/setupProxy.js'