initContainers:
  - name: chaos-init
    image: sidecarinit:andrew
    securityContext:
      runAsUser: 0
      runAsNonRoot: false
      capabilities:
        add:
          - NET_ADMIN
containers:
  - name: chaos-sidecar
    image: envoy:v1
    ports:
    - name: tcp
      containerPort: 10000
    - name: envoy-admin
      containerPort: 18000
    securityContext:
      runAsGroup: 0
      runAsNonRoot: false
      runAsUser: 0
      capabilities:
        add:
        - NET_ADMIN