---
apiVersion: v1
kind: ConfigMap
metadata:
  name: admission-controller-configmaps
  labels:
    app.kubernetes.io/name: {{ template "chaos-operator.name" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: admission-controller
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+"  "_" }}
data:
  sidecar.yaml: |
    name: sidecar
    env:
      - name: HELLO
        value: world
      - name: TEST
        value: test_that
    containers:
    - name: sidecar-nginx
      image: nginx:1.12.2
      imagePullPolicy: IfNotPresent
      ports:
      - containerPort: 80
      env:
        - name: ENV_IN_SIDECAR
          value: test-in-sidecar