apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: chaos-api-server
  labels:
    app.kubernetes.io/name: {{ template "chaos-operator.name" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: api-server
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+"  "_" }}
spec:
  replicas: {{ .Values.apiServer.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ template "chaos-operator.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: api-server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ template "chaos-operator.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: api-server
    spec:
    {{- if .Values.apiServer.serviceAccount }}
      serviceAccount: {{ .Values.apiServer.serviceAccount }}
    {{- end }}
      containers:
      - name: api-server
        image: {{ .Values.apiServer.image  }}
        imagePullPolicy: {{ .Values.apiServer.imagePullPolicy | default "IfNotPresent" }}
        resources:
{{ toYaml .Values.controllerManager.resources | indent 12 }}
        command:
          - /usr/local/bin/chaos-api-server
        volumeMounts:
        - name: data
          mountPath: /data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: api-server-sqlite-pv-claim
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: api-server-sqlite-pv-claim
spec:
  {{- if .Values.apiServer.volume.storageClassName }}
  storageClassName: {{ .Values.apiServer.volume.storageClassName }}
  {{- end }}
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.apiServer.volume.storage }}
  {{- if .Values.apiServer.volume.selector }}
  selector:
    {{ .Values.apiServer.volume.selector }}
  {{- end }}

