---
apiVersion: v1
kind: ConfigMap
metadata:
  name: webhook-configmaps
  labels:
    app.kubernetes.io/name: {{ template "chaos-operator.name" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: webhook
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+"  "_" }}
data:
  chaosfs-tikv.yaml: |
    name: chaosfs-tikv
    initContainers:
    - name: inject-scripts
      image: pingcap/chaos-scripts:latest
      imagePullpolicy: Always
      command: ["sh", "-c", "mkdir -p /tmp/scripts; cp -R /scripts/* /tmp/scripts/; mkdir -p /var/lib/tikv/fuse-data"]
    containers:
    - name: chaosfs
      image: pingcap/chaos-fs
      imagePullpolicy: Always
      ports:
      - containerPort: 65534
      securityContext:
        privileged: true
      command:
        - /usr/local/bin/chaosfs
        - -addr=:65534
        - -pidfile=/tmp/fuse/pid
        - -original=/var/lib/tikv/data
        - -mountpoint=/var/lib/tikv/fuse-data
      volumeMounts:
        - name: tikv
          mountPath: /var/lib/tikv
          mountPropagation: Bidirectional
    volumeMounts:
    - name: tikv
      mountPath: /var/lib/tikv
      mountPropagation: HostToContainer
    - name: scripts
      mountPath: /tmp/scripts
    - name: fuse
      mountPath: /tmp/fuse
    volumes:
    - name: scripts
      emptyDir: {}
    - name: fuse
      emptyDir: {}
    postStart:
      tikv:
        command:
          - /tmp/scripts/wait-fuse.sh
  chaosfs-pd.yaml: |
    name: chaosfs-pd
    initContainers:
    - name: inject-scripts
      image: pingcap/chaos-scripts:latest
      imagePullpolicy: Always
      command: ["sh", "-c", "mkdir -p /tmp/scripts; cp -R /scripts/* /tmp/scripts/; mkdir -p /var/lib/tikv/fuse-data"]
    containers:
    - name: chaosfs
      image: pingcap/chaos-fs
      imagePullpolicy: Always
      ports:
      - containerPort: 65534
      securityContext:
        privileged: true
      command:
        - /usr/local/bin/chaosfs
        - -addr=:65534
        - -pidfile=/tmp/fuse/pid
        - -original=/var/lib/pd/data
        - -mountpoint=/var/lib/pd/fuse-data
      volumeMounts:
        - name: tikv
          mountPath: /var/lib/tikv
          mountPropagation: Bidirectional
    volumeMounts:
    - name: pd
      mountPath: /var/lib/pd
      mountPropagation: HostToContainer
    - name: scripts
      mountPath: /tmp/scripts
    - name: fuse
      mountPath: /tmp/fuse
    volumes:
    - name: scripts
      emptyDir: {}
    - name: fuse
      emptyDir: {}
    postStart:
      pd:
        command:
          - /tmp/scripts/wait-fuse.sh
