---
apiVersion: v1
kind: ConfigMap
metadata:
  name: webhook-configmaps
  labels:
    app.kubernetes.io/name: {{ template "chaos-operator.name" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: webhook
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+"  "_" }}
data:
  chaosfs-tikv.yaml: |
    name: chaosfs-tikv
    initContainers:
    - name: inject-scripts
      image: pingcap/chaos-scripts:latest
      imagePullpolicy: Always
      command: ["sh", "-c", "mkdir -p /tmp/scripts; cp -R /scripts/* /tmp/scripts/"]
    containers:
    - name: chaosfs
      image: pingcap/chaosfs:latest
      imagePullpolicy: Always
      ports:
      - containerPort: 65534
      securityContext:
        privileged: true
        capabilities:
          add:
            - SYS_ADMIN
      command:
        - /usr/local/bin/chaosfs
        - -addr=":65534"
        - -original="/var/lib/tikv/data"
        - -mountpoint="/var/lib/tikv/fuse-data"
    volumeMounts:
    - name: tikv
      mountPath: /var/lib/tikv
      mountPropagation: HostToContainer
    - name: scripts
      mountPath: /tmp/scripts
    volumes:
    - name: scripts
      emptyDir: {}
    postStart:
      tikv:
        command:
          - /tmp/scripts/wait-fuse.sh
  chaosfs-pd.yaml: |
    name: chaosfs-pd
    containers:
    - name: chaosfs
      image: pingcap/chaosfs:latest
      imagePullpolicy: Always
      ports:
      - containerPort: 65534
      securityContext:
        privileged: true
        capabilities:
          add:
            - SYS_ADMIN
      command:
        - /usr/local/bin/chaosfs
        - -addr=":65534"
        - -original="/var/lib/pd/data"
        - -mountpoint="/var/lib/pd/fuse-data"
    volumeMounts:
    - name: pd
      mountPath: /var/lib/pd
      mountPropagation: HostToContainer
