apiVersion: chaos-mesh.org/v1alpha1
kind: JVMChaos
metadata:
  name: jvm-delay4servlet-example
  namespace: chaos-testing
spec:
  action: delay4servlet
  delay4servlet:
    requestpath: /
    time: 10000
  mode: one
  selector:
    labelSelectors:
      "app": "java-demo"
  scheduler:
    cron: "@every 1m"
