apiVersion: pingcap.com/v1alpha1
kind: PodChaos
metadata:
  name: container-kill-example
  namespace: chaos-testing
spec:
  action: container-kill
  mode: one
  containerName: "tidb"
  selector:
    namespaces:
      - default
    labelSelectors:
      "app.kubernetes.io/component": "tidb"
  scheduler:
    cron: "@every 1m"
