apiVersion: v1
kind: Pod
metadata:
  name: shell-demo
  labels:
    name: shell-demo
spec:
  volumes:
    - name: shared-data
      emptyDir: {}
  containers:
    - name: nginx1
      image: nginx:1.18
      volumeMounts:
        - name: shared-data
          mountPath: /usr/share/nginx/html
      ports:
        - containerPort: 80
          hostPort: 8088