apiVersion: pingcap.com/v1alpha1
kind: NetworkChaos
metadata:
  name: network-corrupt-example
  namespace: chaos-testing
spec:
  action: bandwidth
  mode: one
  selector:
    labelSelectors:
      "app.kubernetes.io/component": "tikv"
  bandwidth:
    rate: 10 kbps
    buffer: 1000
    limit: 100
  duration: "10s"
  scheduler:
    cron: "@every 15s"