apiVersion: pingcap.com/v1alpha1
kind: NetworkChaos
metadata:
  name: network-delay-example
  namespace: chaos-testing
spec:
  action: delay
  selector:
    namespaces:
      - tidb-cluster-demo
    labelSelectors:
      "app.kubernetes.io/component": "tikv"
  delay:
    latency: 90000
    correlation: 0.25
    jitter: 90000
  duration: "20s"
  scheduler:
    cron: "@every 30s"
