apiVersion: chaos-mesh.org/v1alpha1
kind: Workflow
metadata:
  name: try-workflow
spec:
  entry: the-entry
  templates:
    - name: the-entry
      template_type: Serial
      duration: 240s
      tasks:
        - prefix-suspending
        - workflow-network-chaos
        - suffix-suspending
        - worklfow-pod-chaos
    - name: prefix-suspending
      template_type: Suspend
      duration: 10s
    - name: workflow-network-chaos
      template_type: NetworkChaos
      duration: 20s
      network_chaos:
        direction: to
        action: delay
        mode: all
        selector:
          labelSelectors:
            "app": "hello-kubernetes"
        delay:
          latency: "90ms"
          correlation: "25"
          jitter: "90ms"
    - name: worklfow-pod-chaos
      template_type: PodChaos
      duration: 40s
      pod_chaos:
        action: pod-kill
        mode: one
        selector:
          labelSelectors:
            "app": "hello-kubernetes"
        scheduler:
          cron: "@every 10s"
    - name: suffix-suspending
      template_type: Suspend
      duration: 5s

