# Copyright 2021 Chaos Mesh Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/chaos-mesh.org_podchaos.yaml
- bases/chaos-mesh.org_networkchaos.yaml
- bases/chaos-mesh.org_iochaos.yaml
- bases/chaos-mesh.org_timechaos.yaml
- bases/chaos-mesh.org_kernelchaos.yaml
- bases/chaos-mesh.org_stresschaos.yaml
- bases/chaos-mesh.org_podiochaos.yaml
- bases/chaos-mesh.org_podhttpchaos.yaml
- bases/chaos-mesh.org_podnetworkchaos.yaml
- bases/chaos-mesh.org_httpchaos.yaml
- bases/chaos-mesh.org_dnschaos.yaml
- bases/chaos-mesh.org_awschaos.yaml
- bases/chaos-mesh.org_jvmchaos.yaml
- bases/chaos-mesh.org_gcpchaos.yaml
- bases/chaos-mesh.org_workflows.yaml
- bases/chaos-mesh.org_workflownodes.yaml
- bases/chaos-mesh.org_schedules.yaml
- bases/chaos-mesh.org_physicalmachinechaos.yaml
# +kubebuilder:scaffold:crdkustomizeresource

patchesStrategicMerge:
# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
# patches here are for enabling the conversion webhook for each CRD
#- patches/webhook_in_podchaos.yaml
#- patches/webhook_in_networkchaos.yaml
#- patches/webhook_in_iochaos.yaml
# +kubebuilder:scaffold:crdkustomizewebhookpatch

# [CERTMANAGER] To enable webhook, uncomment all the sections with [CERTMANAGER] prefix.
# patches here are for enabling the CA injection for each CRD
#- patches/cainjection_in_podchaos.yaml
#- patches/cainjection_in_networkchaos.yaml
#- patches/cainjection_in_iochaos.yaml
# +kubebuilder:scaffold:crdkustomizecainjectionpatch

# the following config is for teaching kustomize how to do kustomization for CRDs.
configurations:
- kustomizeconfig.yaml
