apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
        - args:
            - --storage.tsdb.path=/var/run/prometheus/data
            - --storage.tsdb.retention.time=6h
            - --config.file=/etc/prometheus/prometheus.yml
            - --log.level=debug
          image: quay.io/prometheus/prometheus:v2.15.2
          imagePullPolicy: IfNotPresent
          name: prometheus
          ports:
            - containerPort: 9090
              name: web
              protocol: TCP
          volumeMounts:
            - mountPath: /var/run/prometheus
              name: data
      volumes:
        - emptyDir: {}
          name: data
