apiVersion: apps/v1
kind: Deployment
metadata:
  name: sleep
  namespace: sidecar-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sleep
  template:
    metadata:
      labels:
        app: sleep
      annotations:
        admission-webhook.pingcap.com/request: "sidecar"
    spec:
      containers:
      - name: sleep
        image: tutum/curl
        command: ["/bin/sleep","infinity"]
        imagePullPolicy: IfNotPresent
