name: Unit Test And Code Coverage

on:
  push:
    paths:
      - Makefile
      - go.*
      - "**.go"

permissions: read-all

jobs:
  unitTestAndCodeCoverage:
    name: "Unit Test And Code Coverage"
    steps:
      - uses: actions/checkout@v4

      - name: Unit Test
        run: make test

      - name: Upload Code Coverage
        uses: codecov/codecov-action@v4
        with:
          files: ./cover.out
          verbose: true
          fail_ci_if_error: true
