name: Unit Test And Code Coverage

# this workflow would work on all the branches and all the prs
on:
  push: {}
  pull_request: {}

jobs:
  unitTestAndCodeCoverage:
    name: "Unit Test And Code Coverage"
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: Unit Test
        run: |
          ROOT=$(pwd)
          KUBEBUILDER_ASSETS=${ROOT}/output/bin/kubebuilder/bin make test
      - name: Upload Code Coverage
        uses: codecov/codecov-action@v2
        with:
          files: ./cover.out
          verbose: true
          fail_ci_if_error: true
