# Refer to https://github.com/dcoapp/app/issues/199 for more details.
name: Dummy DCO
on:
  merge_group:

permissions: read-all

jobs:
  DCO:
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' }}
    steps:
      - run: echo "Dummy DCO workflow (it won't run any checks actually) triggered by merge_group in order to pass the merge queue check."
