name: E2E test matrix

on:
  pull_request:
    branches:
      - master
      - release-*

jobs:
  basic:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        kind-version:
          - 0.11.1
        kubernetes-version:
          - v1.20.7
          - v1.21.1
        include:
          - kind-version: 0.8.1
            kubernetes-version: v1.12.10
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Setup Minikube
        uses: manusa/actions-setup-minikube@v2.4.2
        with:
          minikube version: v1.23.0
          kubernetes version: ${{ matrix.kubernetes-version }}
      - name: Setup Helm
        uses: azure/setup-helm@v1
      - name: Enable docker registry for minikube
        run: |
          minikube addons enable registry && \
              docker run --rm -d --network=host alpine ash -c "apk add socat && socat TCP-LISTEN:5000,reuseaddr,fork TCP:$(minikube ip):5000" && \
              kubectl create ns chaos-testing
      - name: Install Chaos Mesh
        run: |
         make prepare-install install

      - name: Prepare e2e images
        run: |
          make prepare-e2e
      - name: e2e tests
        run: |
          KUBECONFIG=~/.kube/config GINKGO_FLAGS=-p make e2e
