name: E2E Test Upload Cache

on:
  workflow_dispatch: {}
  push:
    branches:
      - master
      - release-*
jobs:
  build-image:
    strategy:
      matrix:
        arch: [x86_64, aarch64]
    runs-on: ${{ fromJson('{"x86_64":"ubuntu-latest", "aarch64":["self-hosted", "Linux", "ARM64"]}')[matrix.arch] }}
    steps:
      - name: checkout codes
        uses: actions/checkout@v2
      - name: build e2e images
        env:
          DOCKER_CACHE: 1
          DOCKER_CACHE_DIR: ${{github.workspace}}/cache
          GO_BUILD_CACHE: ${{github.workspace}}/cache
          DOCKER_CLI_EXPERIMENTAL: enabled 
        run: |
          docker buildx create --use --name chaos-mesh-builder
          make -j4 image e2e-image
      - name: upload build cache
        uses: martijnhols/actions-cache/save@main
        with:
          path: cache
          key: e2e-image-build-cache-${{ runner.os }}-${{ matrix.arch }}

  build-e2e-binary:
    strategy:
      matrix:
        arch: [x86_64, aarch64]
    runs-on: ${{ fromJson('{"x86_64":"ubuntu-latest", "aarch64":["self-hosted", "Linux", "ARM64"]}')[matrix.arch] }}
    steps:
      - name: checkout codes
        uses: actions/checkout@v2
      - name: build e2e binary
        env:
          DOCKER_CACHE: 1
          DOCKER_CACHE_DIR: ${{github.workspace}}/cache
          GO_BUILD_CACHE: ${{github.workspace}}/cache
        run: |
          make e2e-build
      - name: upload build cache
        uses: martijnhols/actions-cache/save@main
        with:
          path: cache
          key: e2e-binary-build-cache-${{ runner.os }}-${{ matrix.arch }}

