name: Script Test
on:
  push:
    branches:
      - master
      - release-1.0
  pull_request:
    branches:
      - master
      - release-1.0

jobs:
  run:
    name: Script Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          # Must use at least depth 2!
          fetch-depth: 2

      - name: Creating kind cluster
        uses: helm/kind-action@v1.0.0-rc.1

      - name: Install Chaos Mesh
        run: |
          bash install.sh --local kind --crd ./manifests/crd.yaml
          # TODO: the old version can't handle the webhook for validate authority, so delete it
          # will remove this after the pr #1535 merged
          kubectl delete ValidatingWebhookConfiguration validate-auth -n chaos-testing

      - name: Run integration test
        run: |
          bash test/integration_test/run.sh network
