name: ci

on:
  pull_request:
    branches:
      - master
      - release-*
    paths:
      - "ui/**"
      - "!ui/README.md"
      - "!ui/.*"

jobs:
  pull:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./ui
    strategy:
      matrix:
        job:
          - verify
          - build
          - test
        node-version: ["14"]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"
          cache-dependency-path: "ui/yarn.lock"

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Cache app build
        if: ${{ matrix.job == 'build' }}
        uses: actions/cache@v2
        with:
          path: ./app/build
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Try build
        if: ${{ matrix.job == 'build' }}
        run: yarn build

      - name: Run UT
        if: ${{ matrix.job == 'test' }}
        run: |
          yarn workspace @ui/mui-extends build
          yarn workspace @ui/app test
