name: Upload Image for PR
on:
  issue_comment:
    types: [created]

jobs:
  build-for-pr:
    runs-on: ubuntu-latest
    if: ${{ github.event.issue.pull_request && startsWith( github.event.comment.body, '/build-image') }}
    steps:
      - uses: actions/checkout@master

      - name: Install jq
        run: |
          sudo apt-get install jq -y

      - name: Build Chaos Mesh Build Env
        env:
          IMAGE_BUILD_ENV_BUILD: ${{ contains(github.event.pull_request.labels.*.name, 'rebuild-build-env-image') }}
        run: |
          if [ "${IMAGE_BUILD_ENV_BUILD}" = "true" ] ; then
            export IMAGE_BUILD_ENV_BUILD=1;
          else
            export IMAGE_BUILD_ENV_BUILD=0;
          fi

          make image-build-env

      - name: Build Chaos Mesh Dev Env
        env:
          IMAGE_DEV_ENV_BUILD: ${{ contains(github.event.pull_request.labels.*.name, 'rebuild-dev-env-image') }}
        run: |
          if [ "${IMAGE_DEV_ENV_BUILD}" = "true" ] ; then
            export IMAGE_DEV_ENV_BUILD=1;
          else
            export IMAGE_DEV_ENV_BUILD=0;
          fi

          make image-dev-env
      
      - name: Build Chaos Mesh
        run: |
          make \
            IMAGE_TAG=latest \
            IMAGE_PROJECT=chaos-mesh \
            IMAGE_REGISTRY=ghcr.io \
            UI=1 \
            image
          
          for IMAGE in "chaos-mesh" "chaos-daemon" "chaos-dashboard"
          do
            docker image save ghcr.io/chaos-mesh/$IMAGE > $IMAGE.tar
          done

      - name: Upload Chaos Mesh Image to Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: chaos-mesh-images
          path: |
            *.tar

      - name: Get Artifact URL
        id: get_artifact_url
        env:
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: |
          ARTIFACT_URL=$(curl \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/$GITHUB_REPOSITORY/actions/runs/${{ github.run_id }}/artifacts | jq ".artifacts[0].archive_download_url")
          
          echo "::set-output name=artifact_url::$ARTIFACT_URL"
          echo "ARTIFACT_URL: $ARTIFACT_URL"
      
      - name: Debug
        run: |
          echo '${{ toJSON(steps) }}'
        
      - name: Create comment
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            You can download the image from:
            ${{ steps.get_artifact_url.outputs.artifact_url }}
