name: Upload Env Images
on:
  push:
    paths:
      - 'images/dev-env/Dockerfile'
    branches:
      - master
      - release-*

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          # Must use at least depth 2!
          fetch-depth: 2

      - name: Extract Image Tag
        shell: bash
        run: |
          IMAGE_TAG=${GITHUB_REF##*/}
          if [ "${IMAGE_TAG}" = "master" ] ; then
            IMAGE_TAG=latest; 
          fi

          echo "##[set-output name=image_tag;]$(echo $IMAGE_TAG)"
        id: image_tag

      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Chaos Mesh Env
        env:
          IMAGE_TAG: ${{ steps.image_tag.outputs.image_tag }}
        run: |
          export IMAGE_DEV_ENV_BUILD=1

          make -B TARGET_PLATFORM=amd64 IMAGE_TAG=$IMAGE_TAG-amd64 image-dev-env
          make -B TARGET_PLATFORM=arm64 IMAGE_TAG=$IMAGE_TAG-arm64 image-dev-env

          docker manifest create ghcr.io/chaos-mesh/chaos-mesh/dev-env:$IMAGE_TAG \
            ghcr.io/chaos-mesh/chaos-mesh/dev-env:$IMAGE_TAG-amd64 \
            ghcr.io/chaos-mesh/chaos-mesh/dev-env:$IMAGE_TAG-arm64
          
          docker manifest annotate ghcr.io/chaos-mesh/chaos-mesh/dev-env:$IMAGE_TAG \
            ghcr.io/chaos-mesh/chaos-mesh/dev-env:$IMAGE_TAG-amd64 \
            --os linux --arch x86_64
          docker manifest annotate ghcr.io/chaos-mesh/chaos-mesh/dev-env:$IMAGE_TAG \
            ghcr.io/chaos-mesh/chaos-mesh/dev-env:$IMAGE_TAG-arm64 \
            --os linux --arch arm64

      - name: Upload Chaos Mesh Env
        env:
          IMAGE_TAG: ${{ steps.image_tag.outputs.image_tag }}
        run: |
          docker push ghcr.io/chaos-mesh/chaos-mesh/dev-env:$IMAGE_TAG
